config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :cars
  resources :types
  resources :brands
  
  root 'homepage#index'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :types, dependent: :destroy
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :brand
  belongs_to :type
  has_attached_file :photo, styles: { large:"800x300!",medium: "300x150>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :brand
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :get_brands

  def get_brands
    @brands = Brand.all
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:set_brand,:show]
  before_action :set_brand, only: [:edit,:update,:destroy,:show]
  def index
    @brands = Brand.all
  end

  def show
    @cars = Car.where(brand_id: @brand.id)
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brands_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @brand.update(brand_params)
      redirect_to brands_path, notice: "#{@brand.name} is updated"
    else
      redirect_to brands_path, notice: "Unable to update"
    end
  end

  def destroy
    @brand.destroy
    redirect_to brands_path,notice: "Delete brand successfull"
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end
  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:show,:set_collections,:set_car]
  before_action :set_car, only: [:show,:edit,:destroy,:update]
  before_action :set_collections, only: [:new,:edit]

  def index
    @cars = Car.all
  end

  def show
    @user = User.first
  end

  def new
    @car = Car.new

  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to cars_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car), notice: "Update success"
    else
      render 'edit'
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, notice: "Car has deleted"
  end

  private
  def generate_years difference
    years = []
    difference.times { |i|
      years.push(DateTime.current.year - i)
    }
    years
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand_id,:type_id,:price,:total_distance,:engine_volume,:assembly_year,:purchase_year,:photo)
  end

  def set_collections
    @brands = Brand.all
    @types = Type.all
    @years = generate_years 15
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    # @brands = Brand.all
    @carousel_items = Car.last(3)
    @cars = Car.last(6)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:notice] = "Registration just isn't there yet"
    redirect_to root_path
  end
  private
  def sign_up_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:phone)
  end

  def account_update_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:phone,:address,:current_password)
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:edit,:update,:destroy,:show]
  skip_before_action :authenticate_user!, only: :show
  def new
    @type = Type.new
    @brands = Brand.all
  end

  def show
    @cars = Car.where(type_id: @type.id)
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to brands_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @type.update
      redirect_to brands_path
    else
      render 'edit'
    end
  end

  def destroy
    @type.destroy
    redirect_to brands_path
  end

  private
  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:name,:brand_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/brands/_brand_form.html.erb
  <h3>New/Update Brand</h3>
  <%= form_for @brand do |f| %>
    <%= render "shared/errors", object: @brand %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <%= f.submit "Save Brand", class: "btn btn-primary" %>
  <% end %>

app/views/brands/edit.html.erb
<h1>Edit Brand</h1>
<%= render 'brand_form' %>

app/views/brands/index.html.erb
<div class="col-md-9">
<h1>Car Brands</h1>
<% if user_signed_in? %>
  <%= link_to "Add Car Brand", new_brand_path %>
  <%= link_to "Add Car Type", new_type_path %>
<% end %>
<ul>
  <% @brands.each do |brand| %>
      <li>
        <%= link_to brand.name.to_s.capitalize,brand_path(brand) %>
        <%= link_to("Edit", edit_brand_path(brand)) + ' ' + link_to("Delete", brand_path(brand), method: :delete) if user_signed_in? == true %>
        <ul>
          <% brand.types.each do |type| %>
            <li>
              <%= link_to type.name.to_s.capitalize, type_path(type) %> <%= link_to("Edit", edit_type_path(type)) + ' ' + link_to("Delete", type_path(type), method: :delete) if user_signed_in? == true %>
            </li>
          <% end %>
        </ul>
      </li>
  <% end %>
</ul>
</div>

app/views/brands/new.html.erb
<%= render 'brand_form' %>

app/views/brands/show.html.erb
  <h1><%= "#{@brand.name.capitalize}" %></h1>
  <% unless @cars.nil? %>
  <div class="list-group">
    <% @cars.each do |car| %>
      <%= link_to "#{car.type.name} - #{car.assembly_year.to_s} Rp #{car.price.to_s}", car_path(car), class: "list-group-item list-group-item-info" %>
    <% end %>
  </div>
  <% end %>

app/views/cars/_car_form.html.erb
  <h3>New/Update Car</h3>
  <%= form_for @car do |f| %>
    <%= render "shared/errors", object: @car %>
    <div class="form-group">
      <%= f.label :brand %>
      <%= f.select(:brand_id, options_from_collection_for_select(@brands,"id","name",@car.brand_id),{include_blank: "Select brand",id: "brand_id"},class: "form-control") %>
    </div>
    <div class="form-group">
      <%= f.label :type %>
      <%= f.select(:type_id, options_from_collection_for_select(@types,"id","name",@car.type_id),{include_blank: "Select type",id: "type_id"},class: "form-control") %>
    </div>

    <div class="form-group">
      <%= f.label "Add Photo" %>
      <%= f.file_field :photo, placeholder: "Upload Car Photo",class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :assembly_year %>
      <%= f.select(:assembly_year, options_for_select(@years,@car.assembly_year),{include_blank: "Select year"},class: "form-control") %>
    </div>
    <div class="form-group">
      <%= f.label :purchase_year %>
      <%= f.select(:purchase_year, options_for_select(@years,@car.purchase_year),{include_blank: "Select year"},class: "form-control") %>
    </div>
    <div class="form-group">
      <%= f.label :total_distance %>
      <%= f.number_field :total_distance, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :engine_volume %>
      <%= f.number_field :engine_volume, class: "form-control" %>
    </div>
    <%= f.submit "Save Car",class: "btn btn-primary" %>
  <% end %>

app/views/cars/edit.html.erb
<%= render 'car_form' %>

app/views/cars/index.html.erb
<h1>All Cars</h1>
<ul>
  <% @cars.each do |car| %>
  <li>
    <%= car.brand.name.to_s.capitalize %> - <%= car.type.name.to_s.capitalize %> - <%= car.assembly_year %><br>
    <%= link_to "detail", car_path(car) %> <%= link_to "edit", edit_car_path(car) %> <%= link_to "delete", car_path(car),method: :delete %>
  </li>
  <% end %>
</ul>

app/views/cars/new.html.erb
<%= render 'car_form' %>

app/views/cars/show.html.erb
<div class="col-md-9">

  <div class="thumbnail">
    <%= image_tag @car.photo_file_name.nil? ? "large_notavailable.jpg" : @car.photo.url(:large), class: "img-responsive" %>
    <div class="caption-full">
      <h4 class="pull-right">Rp <%= @car.price.to_s %></h4>
      <h4>
        <a href="#"><%= @car.brand.name %> - <%= @car.type.name %></a>
      </h4>
      <p>
        <ul>
          <li>
            Assembly Year: <%= @car.assembly_year.to_s %>
          </li>
          <li>
            First Purchase Year: <%= @car.purchase_year.to_s %>
          </li>
          <li>
            Total Distance: <%= @car.total_distance.to_s %>
          </li>
          <li>
            Engine Volume: <%= @car.engine_volume.to_s %>
          </li>
        </ul>
        <h3>Get more info:</h3>
        Contact:
        <ul>
          <li>
            Name: <%= @user.name.capitalize %>
          </li>
          <li>
            Phone: <%= @user.phone %>
          </li>
        </ul>
      </p>
    </div>
  </div>
</div>

app/views/homepage/index.html.erb
<div class="col-md-9">

  <div class="row carousel-holder">

    <div class="col-md-12">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @carousel_items.count.times do |i| %>
              <li data-target="#carousel-example-generic" data-slide-to="<%= i %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% @carousel_items.each_with_index do |car,index| %>
              <% if index == 0 %>
                <div class="item active">
              <% else %>
                  <div class="item">
              <% end %>
                <%= image_tag car.photo_file_name.nil? ? "large_notavailable.jpg" : car.photo.url(:medium), class: "slide-image" %>
              </div>
            <% end %>
          </div>
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
    </div>

  </div>

  <div class="row">
    <% @cars.each do |car| %>
      <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail thumbnail-home">
          <%= image_tag car.photo_file_name.nil? ? "small_notavailable.jpg" : car.photo.url(:medium) %>
          <div class="caption">
            <a href="<%= car_path(car) %>"><h4 class="pull-right"><%= car.type.name %></h4>
            <h4><%= car.brand.name %></a>
            </h4>
            <ul>
              <li>
                Assembly Year: <%= car.assembly_year.to_s %>
              </li>
              <li>
                Price: <%= car.price.to_s %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Carforsale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "CarForSale",root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "All Brands & Type", brands_path %>
          </li>
          <%= render 'devise/shared/links' %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <p class="notice">
        <%= notice %>
      </p>
      <p class="alert">
        <%= alert %>
      </p>
      <div class="col-md-3">
        <p class="lead">CarForSale</p>
        <div class="list-group">
          <% @brands.each do |brand| %>
            <%= link_to brand.name.to_s.capitalize, brand_path(brand), class: "list-group-item" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-9">
        <%= yield %>
      </div>
    </div>
    <!-- /.container -->
  </div>

  <div class="container">

    <hr>

    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; CarForSale 2015</p>
        </div>
      </div>
    </footer>

  </div>
  <!-- /.container -->
</body>

</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <strong><%= pluralize object.errors.count,"error" %></strong>
    please check your input
    <ul>
      <% form_object.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/types/_type_form.html.erb
<h3>New/Update Type</h3>
<%= form_for @type do |f| %>
  <%= render "shared/errors", object: @type %>
  <div class="form-group">
    <%= f.label "Select brand:" %>
    <%= f.select :brand_id, options_from_collection_for_select(@brands,"id","name",@type.brand_id),{include_blank: "Select brand", id: "brand_id"},class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Save Type", class: "btn btn-primary" %>
<% end %>

app/views/types/edit.html.erb
<%= render 'type_form' %>

app/views/types/new.html.erb
<%= render 'type_form' %>

app/views/types/show.html.erb
  <h3><%= "#{@type.brand.name.capitalize} - #{@type.name.capitalize}" %></h3>
  <% unless @car.nil? %>
    <div class="list-group">
      <% @cars.each do |car| %>
        <%= link_to "#{car.type.name} - #{car.assembly_year.to_s} Rp #{car.price.to_s}", car_path(car), class: "list-group-item list-group-item-info" %>
      <% end %>
    </div>
  <% end %>